### PR TITLE
New outline footprints and update acknowledgements

### PR DESCRIPTION
**Pull request by glikely**
Hi folks,

I've created 3 new footprints containing the outlines, zones and mounting holes for each of the CE board sizes. Using one of these footprints makes it really easy to make sure connectors and components are positioned correctly. I've updated the template PCB to use the CE standard size footprint and a note about how to use the Extended-A and Extended-B outlines.

The pull request also includes an update to the acknowledgements list to include both Sophie and me who created the KiCad template in the first place.

### CODE REVIEW

**Comment by sdrobertw** [comment]
Thanks, Grant! Yes, You and Sophie should be in the contributor list for sure... Sorry for not adding this sooner.

Michael Welling is the one who currently approves all PR, I am sure he will get to this soon.

**Comment by mwelling** [comment]
Okay. I have taken a look at the patterns and am trying to understand the specification in terms of the extended form factor. It seems the extended A and extended B have the same form-factor but the extended B allows for the maximum height to be 15mm instead of 6.5mm.

Your pattern for extended A seems to stops and the end of the checkered area that denotes:
Extended area see specification for height restrictions: “Extended A” max 6.5mm or “Extended B” max 15.0mm"

To me it seems that the Extended A would allow for the mezzanine to go all the way to the 100mm edge and the Extended B would not. On the patterns the A is cutoff at 81.5mm and B goes to 100mm but says that a cutout is needed. This seems a bit backwards.

Can we combine the extended A and B patterns and add notes for explaining the height requirements?

**Comment by mwelling** [comment]
@glikely Any progress/feedback?

**Comment by mwelling** [comment]
Just going to merge this for now. Can do follow up requests when/if you look at my comments.

**Comment by glikely** [comment]
Hi Michael, I only just saw your question now. I may have misinterpreted the meaning of extended A/B. I had thought that extended A meant an 85x81.5 board, and extended B meant 85x100. Mostly that came from how the diagram is laid out. However, reading again I can see that both may be 85x100 and the only difference is the height restriction between the two.

I'm happy to change the layout, but I'd like to have the spec clarified so it is accurate. :-)

**Comment by glikely** [comment]
Okay, I think understand what it should be now. All extended boards are 85x100, but the extended B option allows for 15mm components in the rear connector area. That means a mezzanine needs to either not extend into that area, or the mezzanine needs to be mounted on extension connectors to make it sit 15mm above the baseboard.

Yes, I think I can rework the template to show this with a single model.

**Comment by mwelling** [comment]
Thanks. Clarifying the specification (or driving someone to do so) would also be greatly appreciated.

**Comment by Yang-96Boards** [comment]
Ack

**Comment by Yang-96Boards** [comment]
Just reviewed this part of spec, indeed as Grant says, the only difference
between A and B is to allow for different heights. All extended boards are
85x100mm. This should be clear from page 26 of the drawing. But please do
let me know if otherwise.

Thanks
Yang



ᐧ

**Pull request merged**
