### PR TITLE
sx1509 i2c gpio expansion mezzanine

### LINKED ISSUE #19: GPIO Expansion Mezz with 5v level shifting
This is a possible solution to the problem of getting arduino based 5v sensors to wok with 1v8 gpios on the 96boards platform.
The suggestion is to use a single 6-8 channel Logic level shifter to shift both i2c and uart pins to 5v and add a gpio expander like a [SX1509](https://cdn.sparkfun.com/assets/learn_tutorials/4/3/4/sx150x_789.pdf) to add 5v gpios.
This would not effect the on-board gpios on the LS, and we will also get additional 5v compatible GPIO pins.
The recommendation is to use a 2.54mm pitch for the additional gpio pin out in order to have compatibility with the readily available adruino based hardware.

### PR DESCRIPTION
**Pull request by ric96**
This mezzanine uses the SX1509 GPIO expation IC to provide
2 banks with 8 GPIOs each for a total of 16 GPIOs.
Each bank can operate at a differnt vcc.

fixes #19

Signed-off-by: Sahaj Sarup <sahajsarup@linaro.org>

### CODE REVIEW

**Comment by mwelling** [comment]
It is expansion not expantion.

I will take a closer look at the files shortly.

**Comment by mwelling** [comment]
There is a P3 on the PCB that is not on the schematic.

The I2C connections on the high speed header appear to be wrong:
image

image

It would be better to use a more regular pattern for connecting the top and bottom connectors. Try adjusting the grid to try and make the vias line up better.

Move the following via further so it not on the pad:
image

The pin number ordering on the board connector do not appear to match the schematic for J1 and J2
image
image

**Comment by mwelling** [comment]
The orientation of the stacking highspeed header seems wrong.
image
image

The silkscreen outline for U1 on the opposite side of the board not necessary.
image

**Comment by ric96** [comment]
@mwelling 
- Removed HS Header
- Brought silkscreen for U1 to Front Layer

**Pull request merged**
